name: Update RSS
on:
  schedule:
    - cron: '0 * * * *' # На всеки час
  workflow_dispatch: # Позволява ви да го пуснете ръчно с бутон

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Libraries
        run: pip install requests beautifulsoup4 feedgen
      - name: Run Scraper
        run: python scraper.py
      - name: Save Result
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add feed.xml
          git commit -m "Auto-update RSS" || exit 0
          git push
